# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detections.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'detections.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x65tections.proto\x12\x06shaggy\"\xf9\x01\n\nDetections\x12\x19\n\x0c\x66rame_number\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x19\n\x0cpublish_rate\x18\x03 \x01(\x02H\x01\x88\x01\x01\x12\x16\n\tnum_beams\x18\x04 \x01(\x05H\x02\x88\x01\x01\x12\x16\n\tnum_times\x18\x05 \x01(\x05H\x03\x88\x01\x01\x12\x17\n\nnum_angles\x18\x06 \x01(\x05H\x04\x88\x01\x01\x12\x0f\n\x07samples\x18\x07 \x03(\x02\x12\x0e\n\x06\x61ngles\x18\x08 \x03(\x02\x42\x0f\n\r_frame_numberB\x0f\n\r_publish_rateB\x0c\n\n_num_beamsB\x0c\n\n_num_timesB\r\n\x0b_num_anglesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detections_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTIONS']._serialized_start=29
  _globals['_DETECTIONS']._serialized_end=278
# @@protoc_insertion_point(module_scope)
