# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: samples.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'samples.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsamples.proto\x12\x06shaggy\"\xb5\x01\n\x07Samples\x12\x19\n\x0c\x66rame_number\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x1a\n\rnum_samples_0\x18\x04 \x01(\x05H\x01\x88\x01\x01\x12\x1b\n\x0enum_channels_1\x18\x05 \x01(\x05H\x02\x88\x01\x01\x12\x14\n\x07samples\x18\x08 \x01(\x0cH\x03\x88\x01\x01\x42\x0f\n\r_frame_numberB\x10\n\x0e_num_samples_0B\x11\n\x0f_num_channels_1B\n\n\x08_samplesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'samples_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAMPLES']._serialized_start=26
  _globals['_SAMPLES']._serialized_end=207
# @@protoc_insertion_point(module_scope)
