# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stft.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'stft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nstft.proto\x12\x06shaggy\"\x82\x02\n\x04STFT\x12\x19\n\x0c\x66rame_number\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x0bnum_times_0\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x14\n\x07num_fft\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x18\n\x0bsample_rate\x18\x04 \x01(\x05H\x03\x88\x01\x01\x12\x1a\n\rnum_channel_2\x18\x05 \x01(\x05H\x04\x88\x01\x01\x12\x19\n\x0cstft_samples\x18\x06 \x01(\x0cH\x05\x88\x01\x01\x42\x0f\n\r_frame_numberB\x0e\n\x0c_num_times_0B\n\n\x08_num_fftB\x0e\n\x0c_sample_rateB\x10\n\x0e_num_channel_2B\x0f\n\r_stft_samplesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STFT']._serialized_start=23
  _globals['_STFT']._serialized_end=281
# @@protoc_insertion_point(module_scope)
